### ISSUE TITLE
crashed when "toutchscreen settings" button in menu was pressed

### ISSUE THREAD

**Issue by nikdo3** [davidsaltacc/touchscreenfix#1]
I have lenovo yoga 2 pro
the crash happens right after I press the button

here's my log
https://mclo.gs/AZVewig

**Comment by davidsaltacc** [comment]
my fault. i listed the mod as working for 1.20.1-1.20.4, when it currently only works for 1.20.1. my bad! ill fix it soon.

**Comment by davidsaltacc** [comment]
The version for 1.20.4 works too now. you can download it here

https://modrinth.com/mod/touchscreenfix/version/biX9lSDf

**Comment by Ahmet53535353** [comment]
> 1.20.4 sürümü de artık çalışıyor. Buradan indirebilirsiniz.
> 
> [https://modrinth.com/mod/dokunmatikekrandüzeltmesi/sürüm/biX9lSDf](https://modrinth.com/mod/touchscreenfix/version/biX9lSDf)
Is the "TouchscreenFix" mod still being developed?
